import type {
  IListSeatBusiness, IListSeatEconomy,
} from '@/model';

export const LIST_DATA_SEAT_BUSINESS: IListSeatBusiness = [
  {
    row: 1,
    seat1: false,
    seat2: true,
    seat3: true,
    seat4: false,
  },
  {
    row: 2,
    seat1: true,
    seat2: true,
    seat3: true,
    seat4: true,
  },
  {
    row: 3,
    seat1: false,
    seat2: false,
    seat3: true,
    seat4: false,
  },
  {
    row: 4,
    seat1: true,
    seat2: true,
    seat3: true,
    seat4: true,
  },
  {
    row: 5,
    seat1: false,
    seat2: true,
    seat3: false,
    seat4: false,
  },
];

export const LIST_DATA_SEAT_ECONOMY:IListSeatEconomy = [
  [
    {
      row: 6,
      seat1: false,
      seat2: true,
      seat3: false,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 7,
      seat1: true,
      seat2: true,
      seat3: false,
      seat4: true,
      seat5: true,
      seat6: false,
    },
    {
      row: 8,
      seat1: false,
      seat2: false,
      seat3: true,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 9,
      seat1: true,
      seat2: false,
      seat3: true,
      seat4: true,
      seat5: false,
      seat6: true,
    },
    {
      row: 10,
      seat1: true,
      seat2: true,
      seat3: true,
      seat4: false,
      seat5: false,
      seat6: true,
    },
    {
      row: 11,
      seat1: false,
      seat2: true,
      seat3: false,
      seat4: true,
      seat5: true,
      seat6: false,
    },
    {
      row: 12,
      seat1: true,
      seat2: true,
      seat3: true,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 13,
      seat1: true,
      seat2: false,
      seat3: true,
      seat4: false,
      seat5: false,
      seat6: true,
    },
  ],
  [
    {
      row: 14,
      seat1: true,
      seat2: true,
      seat3: true,
      seat4: false,
      seat5: false,
      seat6: true,
    },
    {
      row: 15,
      seat1: false,
      seat2: true,
      seat3: false,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 16,
      seat1: true,
      seat2: true,
      seat3: false,
      seat4: true,
      seat5: false,
      seat6: true,
    },
    {
      row: 17,
      seat1: false,
      seat2: true,
      seat3: true,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 18,
      seat1: true,
      seat2: true,
      seat3: true,
      seat4: true,
      seat5: true,
      seat6: true,
    },
  ],
  [
    {
      row: 19,
      seat1: true,
      seat2: true,
      seat3: true,
      seat4: true,
      seat5: true,
      seat6: false,
    },
    {
      row: 20,
      seat1: false,
      seat2: true,
      seat3: true,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 21,
      seat1: true,
      seat2: false,
      seat3: false,
      seat4: true,
      seat5: false,
      seat6: true,
    },
    {
      row: 22,
      seat1: true,
      seat2: true,
      seat3: false,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 23,
      seat1: false,
      seat2: true,
      seat3: false,
      seat4: false,
      seat5: true,
      seat6: false,
    },
    {
      row: 24,
      seat1: true,
      seat2: true,
      seat3: false,
      seat4: true,
      seat5: false,
      seat6: true,
    },
    {
      row: 25,
      seat1: false,
      seat2: false,
      seat3: true,
      seat4: true,
      seat5: true,
      seat6: false,
    },
    {
      row: 26,
      seat1: true,
      seat2: false,
      seat3: true,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 27,
      seat1: false,
      seat2: true,
      seat3: false,
      seat4: false,
      seat5: true,
      seat6: true,
    },
    {
      row: 28,
      seat1: true,
      seat2: true,
      seat3: true,
      seat4: true,
      seat5: true,
      seat6: true,
    },
  ],
  [
    {
      row: 29,
      seat1: true,
      seat2: false,
      seat3: false,
      seat4: true,
      seat5: true,
      seat6: true,
    },
    {
      row: 30,
      seat1: true,
      seat2: true,
      seat3: true,
      seat4: true,
      seat5: true,
      seat6: true,
    },
    {
      row: 31,
      seat1: false,
      seat2: true,
      seat3: true,
      seat4: true,
      seat5: false,
      seat6: true,
    },
    {
      row: 32,
      seat1: true,
      seat2: false,
      seat3: true,
      seat4: true,
      seat5: true,
      seat6: false,
    },
    {
      row: 33,
      seat1: true,
      seat2: true,
      seat3: true,
      seat4: true,
      seat5: false,
      seat6: false,
    },
  ],
];
