import type { IListFlightInfo } from '@/model/flight';
import avtFlight from '/images/avt-flight.png';

export const LIST_DATA_DEPARTURE: IListFlightInfo = [
  {
    srcImage: avtFlight,
    key: '1',
    departure: '7:00AM',
    arrival: '4:15PM',
    duration: '16h 45m',
    stops: '1 stop',
    price: '$624',
    airline: 'Hawaiian Airlines',
    time: '2h 45m in HNL',
    trip: 'round trip',
    value: 'value',
    tax: '$503',
    code: 'FIG4312',
  },
  {
    srcImage: avtFlight,
    key: '2',
    departure: '8:30AM',
    arrival: '6:45PM',
    duration: '18h 15m',
    stops: '2 stops',
    price: '$699',
    airline: 'Delta Air Lines',
    time: '3h 30m in ATL, 4h 15m in LAX',
    trip: 'one way',
    value: 'premium',
    tax: '$527',
    code: 'DLG8921',
  },
  {
    srcImage: avtFlight,
    key: '3',
    departure: '10:15AM',
    arrival: '8:30PM',
    duration: '17h 15m',
    stops: '1 stop',
    price: '$575',
    airline: 'American Airlines',
    time: '2h 30m in DFW',
    trip: 'round trip',
    value: 'economy',
    tax: '$510',
    code: 'AAL7245',
  },
  {
    srcImage: avtFlight,
    key: '4',
    departure: '9:45AM',
    arrival: '7:30PM',
    duration: '15h 45m',
    stops: '1 stop',
    price: '$549',
    airline: 'United Airlines',
    time: '2h 15m in DEN',
    trip: 'one way',
    value: 'standard',
    tax: '$480',
    code: 'UAL3621',
  },
  {
    srcImage: avtFlight,
    key: '5',
    departure: '11:30AM',
    arrival: '9:45PM',
    duration: '16h 15m',
    stops: '1 stop',
    price: '$599',
    airline: 'Southwest Airlines',
    time: '3h 45m in PHX',
    trip: 'round trip',
    value: 'economy',
    tax: '$515',
    code: 'SWA5218',
  },
  {
    srcImage: avtFlight,
    key: '6',
    departure: '6:15AM',
    arrival: '3:45PM',
    duration: '17h 30m',
    stops: '1 stop',
    price: '$609',
    airline: 'JetBlue Airways',
    time: '2h 30m in JFK',
    trip: 'round trip',
    value: 'economy',
    tax: '$525',
    code: 'JBA7123',
  },
  {
    srcImage: avtFlight,
    key: '7',
    departure: '3:45PM',
    arrival: '1:00AM',
    duration: '18h 15m',
    stops: '2 stops',
    price: '$679',
    airline: 'Alaska Airlines',
    time: '3h 15m in SEA, 4h 45m in SFO',
    trip: 'one way',
    value: 'premium',
    tax: '$535',
    code: 'ALK9624',
  },
  {
    srcImage: avtFlight,
    key: '8',
    departure: '5:30PM',
    arrival: '3:00AM',
    duration: '17h 30m',
    stops: '1 stop',
    price: '$599',
    airline: 'Spirit Airlines',
    time: '2h 30m in LAS',
    trip: 'round trip',
    value: 'economy',
    tax: '$520',
    code: 'SPI8235',
  },
  {
    srcImage: avtFlight,
    key: '9',
    departure: '2:15PM',
    arrival: '12:30AM',
    duration: '18h 15m',
    stops: '2 stops',
    price: '$689',
    airline: 'Frontier Airlines',
    time: '3h 30m in DEN, 4h 45m in ORD',
    trip: 'one way',
    value: 'standard',
    tax: '$540',
    code: 'FRA4156',
  },
  {
    srcImage: avtFlight,
    key: '10',
    departure: '12:30PM',
    arrival: '10:45PM',
    duration: '16h 15m',
    stops: '1 stop',
    price: '$639',
    airline: 'Virgin America',
    time: '2h 15m in LAX',
    trip: 'round trip',
    value: 'economy',
    tax: '$515',
    code: 'VAA6237',
  },
  {
    srcImage: avtFlight,
    key: '11',
    departure: '9:15AM',
    arrival: '7:30PM',
    duration: '15h 15m',
    stops: '1 stop',
    price: '$549',
    airline: 'JetBlue Airways',
    time: '2h 45m in JFK',
    trip: 'one way',
    value: 'value',
    tax: '$495',
    code: 'JBA9321',
  },
  {
    srcImage: avtFlight,
    key: '12',
    departure: '7:30AM',
    arrival: '5:45PM',
    duration: '16h 15m',
    stops: '1 stop',
    price: '$589',
    airline: 'Southwest Airlines',
    time: '3h 15m in HOU',
    trip: 'round trip',
    value: 'economy',
    tax: '$510',
    code: 'SWA7643',
  },
  {
    srcImage: avtFlight,
    key: '13',
    departure: '4:45PM',
    arrival: '3:00AM',
    duration: '18h 15m',
    stops: '2 stops',
    price: '$679',
    airline: 'American Airlines',
    time: '3h 30m in DFW, 4h 45m in MIA',
    trip: 'one way',
    value: 'premium',
    tax: '$550',
    code: 'AAL5721',
  },
  {
    srcImage: avtFlight,
    key: '14',
    departure: '8:00AM',
    arrival: '6:15PM',
    duration: '17h 15m',
    stops: '1 stop',
    price: '$599',
    airline: 'Delta Air Lines',
    time: '2h 30m in ATL',
    trip: 'round trip',
    value: 'economy',
    tax: '$520',
    code: 'DLG6218',
  },
  {
    srcImage: avtFlight,
    key: '15',
    departure: '10:30AM',
    arrival: '8:45PM',
    duration: '17h 15m',
    stops: '1 stop',
    price: '$579',
    airline: 'United Airlines',
    time: '2h 30m in ORD',
    trip: 'round trip',
    value: 'value',
    tax: '$505',
    code: 'UAL8319',
  },
];

export const LIST_DATA_RETURN: IListFlightInfo = [
  {
    srcImage: avtFlight,
    key: '1',
    departure: '7:00AM',
    arrival: '4:15PM',
    duration: '16h 45m',
    stops: '1 stop',
    price: '$624',
    airline: 'Hawaiian Airlines',
    time: '2h 45m in HNL',
    trip: 'round trip',
    value: 'value',
    tax: '$503',
    code: 'FIG4312',
  },
  {
    srcImage: avtFlight,
    key: '2',
    departure: '8:30AM',
    arrival: '6:45PM',
    duration: '18h 15m',
    stops: '2 stops',
    price: '$699',
    airline: 'Delta Air Lines',
    time: '3h 30m in ATL, 4h 15m in LAX',
    trip: 'one way',
    value: 'premium',
    tax: '$527',
    code: 'DLG8921',
  },
  {
    srcImage: avtFlight,
    key: '3',
    departure: '10:15AM',
    arrival: '8:30PM',
    duration: '17h 15m',
    stops: '1 stop',
    price: '$575',
    airline: 'American Airlines',
    time: '2h 30m in DFW',
    trip: 'round trip',
    value: 'economy',
    tax: '$510',
    code: 'AAL7245',
  },
  {
    srcImage: avtFlight,
    key: '4',
    departure: '9:45AM',
    arrival: '7:30PM',
    duration: '15h 45m',
    stops: '1 stop',
    price: '$549',
    airline: 'United Airlines',
    time: '2h 15m in DEN',
    trip: 'one way',
    value: 'standard',
    tax: '$480',
    code: 'UAL3621',
  },
  {
    srcImage: avtFlight,
    key: '5',
    departure: '11:30AM',
    arrival: '9:45PM',
    duration: '16h 15m',
    stops: '1 stop',
    price: '$599',
    airline: 'Southwest Airlines',
    time: '3h 45m in PHX',
    trip: 'round trip',
    value: 'economy',
    tax: '$515',
    code: 'SWA5218',
  },
  {
    srcImage: avtFlight,
    key: '6',
    departure: '6:15AM',
    arrival: '3:45PM',
    duration: '17h 30m',
    stops: '1 stop',
    price: '$609',
    airline: 'JetBlue Airways',
    time: '2h 30m in JFK',
    trip: 'round trip',
    value: 'economy',
    tax: '$525',
    code: 'JBA7123',
  },
  {
    srcImage: avtFlight,
    key: '7',
    departure: '3:45PM',
    arrival: '1:00AM',
    duration: '18h 15m',
    stops: '2 stops',
    price: '$679',
    airline: 'Alaska Airlines',
    time: '3h 15m in SEA, 4h 45m in SFO',
    trip: 'one way',
    value: 'premium',
    tax: '$535',
    code: 'ALK9624',
  },
  {
    srcImage: avtFlight,
    key: '8',
    departure: '5:30PM',
    arrival: '3:00AM',
    duration: '17h 30m',
    stops: '1 stop',
    price: '$599',
    airline: 'Spirit Airlines',
    time: '2h 30m in LAS',
    trip: 'round trip',
    value: 'economy',
    tax: '$520',
    code: 'SPI8235',
  },
  {
    srcImage: avtFlight,
    key: '9',
    departure: '2:15PM',
    arrival: '12:30AM',
    duration: '18h 15m',
    stops: '2 stops',
    price: '$689',
    airline: 'Frontier Airlines',
    time: '3h 30m in DEN, 4h 45m in ORD',
    trip: 'one way',
    value: 'standard',
    tax: '$540',
    code: 'FRA4156',
  },
];
